---

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
  release:
    types:
      - 'created'
  schedule:
    # Every Sunday at 05:10
    - cron: '10 5 * * 0'

name: 🔍 Continuous integration

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: 📦 Install goss
        uses: e1himself/goss-installation-action@v1.1.0

      - name: 📦 Check out the codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ### For Cross Platform OSX builds uncomment these lines
      - name: 🖥️ Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: 🚀 Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: 🛠️ Prepare environment
        run: |
          docker network create ss_network
          make env
        env:
          COMPOSE_PROJECT_NAME: wod

      - name: 🧪 Run dcgoss tests
        run: |
          docker network create shared
          make test

...
